export const COLOMBIA: Record<string, string[]> = {
  "Amazonas": ["Leticia", "Puerto Nariño"],
  "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Rionegro", "Apartadó", "Turbo", "Caucasia", "Copacabana", "La Estrella", "Sabaneta", "Caldas", "Marinilla", "El Bagre"],
  "Arauca": ["Arauca", "Saravena", "Tame", "Fortul"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Puerto Colombia", "Galapa"],
  "Bogotá D.C.": ["Bogotá"],
  "Bolívar": ["Cartagena", "Magangué", "El Carmen de Bolívar", "Mompox", "Turbaco"],
  "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva"],
  "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Riosucio", "Villamaría"],
  "Caquetá": ["Florencia", "San Vicente del Caguán", "Puerto Rico"],
  "Casanare": ["Yopal", "Aguazul", "Villanueva", "Tauramena"],
  "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía"],
  "Cesar": ["Valledupar", "Aguachica", "Bosconia", "La Jagua de Ibirico"],
  "Chocó": ["Quibdó", "Istmina", "Condoto"],
  "Córdoba": ["Montería", "Lorica", "Cereté", "Sahagún", "Montelíbano"],
  "Cundinamarca": ["Soacha", "Fusagasugá", "Zipaquirá", "Facatativá", "Chía", "Cajicá", "Mosquera", "Girardot", "Madrid", "Funza", "Tocancipá", "La Calera"],
  "Guainía": ["Inírida"],
  "Guaviare": ["San José del Guaviare", "Calamar"],
  "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Fonseca", "San Juan del Cesar"],
  "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "El Banco"],
  "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "Cumaral"],
  "Nariño": ["Pasto", "Ipiales", "Tumaco", "Túquerres", "La Unión"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios", "El Zulia"],
  "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez"],
  "Quindío": ["Armenia", "Calarcá", "Montenegro", "La Tebaida", "Circasia"],
  "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Marsella"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  "Santander": ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil", "Socorro"],
  "Sucre": ["Sincelejo", "Corozal", "Sampués", "San Marcos"],
  "Tolima": ["Ibagué", "Espinal", "Honda", "Líbano", "Melgar", "Girardot"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Cartago", "Buga", "Jamundí", "Yumbo", "Candelaria", "Pradera"],
  "Vaupés": ["Mitú"],
  "Vichada": ["Puerto Carreño"],
}

export const DEPARTAMENTOS = Object.keys(COLOMBIA).sort()
